name = "backend"
compatibility_date = "2023-12-01"
compatibility_flags = [ "nodejs_compat" ]

kv_namespaces = [
  { binding = "RATE_LIMITER", id = "0cbc0bb07e6049cea50aa0f610ccfe7e" }
]

 [vars]

 DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMjMwMTJiMmEtYjc5MS00MjBjLWI2NmQtMjRmNzIzMWI4NTdkIiwidGVuYW50X2lkIjoiOGFhM2U1YzBhZjNlMzkxZGZlMDYyOTIyOTdlNjA0NDRhYjU3OWIxYmYwYmExNjk3OWFlYmUwNDU3NGQyNDA5MSIsImludGVybmFsX3NlY3JldCI6ImM2YjI5OGQwLTU5ZTEtNDFjMC04MzZhLTU4M2ZjZmMxNjY0YSJ9.LXtBpx4WEkARZMV5lN3-RyULkwzRMd-_PrQqR133FSo"
JWT_SECRET="fsjinjoibjgosjmkjgaonkjgfogjkofjhsjhkfgb"
UPLOADCARE_PUBLIC_KEY="6ef13ff68f8295335e99"
UPLOADCARE_SECRET_KEY="2ee8f547a494626d0c1d"
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"